In [6]:
import numpy as np

## Min function

In [18]:
def min(X):
    """Returns the minimum value. """
    X.sort()
    return X.flatten()[0]

In [19]:
X = np.arange(9).reshape(3, 3)

In [20]:
X.min() == min(X)

True

## Max Function implementation

In [22]:
def max(X):
    """Returns the maximum value. """
    X.sort()
    Xmax = X.flatten()[-1]
    return 

In [23]:
X = np.arange(9).reshape(3, 3)

In [24]:
X.max == max(X)

False

## Argmin Function implmentation

In [39]:
def argmin(X):
    """Returns the indices of the minimum value. """
    flatten_matrix = X.flatten()
    min_value = flatten_matrix.min()
    return flatten_matrix.tolist().index(min_value)
    

In [40]:
X = np.arange(9).reshape(3, 3)

In [41]:
X.argmin() == argmin(X)

True

## Argmax Function Implementation

In [44]:
def argmax(X):
    """Returns the indices of the maximum value. """
    flatten_matrix = X.flatten()
    max_value = flatten_matrix.max()
    return flatten_matrix.tolist().index(max_value)

In [45]:
X = np.arange(9).reshape(3, 3)

In [47]:
X.argmax() == argmax(X)

True

## Transpose of a Matrix

In [66]:
def transpose(X):
    """ Returns the transpose of the 2d matrix. """
    transposed_matrix = np.zeros(X.shape)
    print (X.shape)
    rows, cols = X.shape
    for i in range(rows):
        for j in range(cols):
            transposed_matrix[j][i] = X[i][j]
    return transposed_matrix

In [67]:
X = np.arange(9).reshape(3, 3)

In [71]:
X.T == transpose(X)

(3, 3)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## Inverse of a matrix

In [124]:
from numpy.linalg import inv
from numpy.linalg import det

In [126]:
M = np.array([[3, 5, 6], [4, 2, 3], [5, 2, 9]])

array([[3],
       [9]])

In [128]:
M[1:-1,1:-1]

array([[2]])

In [102]:
np.matrix(M).getH() / det(M)

matrix([[-0.03703704, -0.04938272, -0.0617284 ],
        [-0.0617284 , -0.02469136, -0.02469136],
        [-0.07407407, -0.03703704, -0.11111111]])

In [104]:
det(M)

-80.999999999999957

In [ ]:
def minor(M, i, j):
    return arr[np.array(range(i)+range(i+1, arr.shape[0]))]

In [ ]:
def cofactor(M):
    """Returns the cofactor of a 2d Matrix. """
    cofactor_matrix = np.zeros(M.shape)
    rows,cols = M.shape
    for i in range(rows):
        for j in range(cols):
            cofactor_matrix[i][j] = M[1:,1:]

## Flatten Implementation

In [73]:
def flatten(X):
    """Returns the flatten matrix. """
    # np.nditer iterates over an iterable array and then
    return np.fromiter(np.nditer(X), X.dtype)

In [74]:
M = np.arange(9).reshape(3, 3)

In [75]:
flatten(M) == M.flatten()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

## Dot Product

In [80]:
def dot(X, Y):
    """Returns the dot product. """
    Xrows, Xcols = X.shape
    Yrows, Ycols = Y.shape
    DotProduct = np.zeros(shape=(Xrows, Ycols))
    if Xcols == Yrows:
        for i in range(Xrows):
            for j in range(Xcols):
                sum = 0
                for k in range(Yrows):
                    sum += X[i][k] * Y[k][j]
                DotProduct[i][j] = sum
        return DotProduct
    else:
        
                
    

In [84]:
X = np.arange(9).reshape(3, 3)
Y = np.arange(9).reshape(3, 3)

In [85]:
dot(X, Y) == X.dot(Y)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## Arange followed by reshaper

In [143]:
def arange_reshape(start, stop, shape):
    rows, cols = shape
    matrix = np.zeros(shape)
    range_of_numbers = list(range(start, stop))
    diff = stop - start
    if(diff == shape[0]*shape[1]):
        it = iter(range_of_numbers)
        for i in range(rows):
            for j in range(cols):
                matrix[i][j] = it.__next__()
        return matrix
    else:
        print("Total size of new array should be unchanged")

In [150]:
arange_reshape(2, 6, (2, 2)) == np.arange(start=2,stop=6,step=1).reshape(2, 2)

array([[ True,  True],
       [ True,  True]], dtype=bool)

## Argsort

In [195]:
def argsort(X, axis=1):
    argsorted = []
    Xrows = X.shape[0]
    Xshape = X.shape
    if(X.ndim == 1):
        X = [X]
        Xrows = 1
    if (axis == 0):
        print("Axis")
        X = X.T
    for i in range(Xrows):
        row = X[i].tolist()
        row.sort()
        for j in np.nditer(X[i]):
            argsorted.append(row.index(j))
    if(axis == 0):
        print("Axis")
        return np.asarray(argsorted).reshape(Xshape).T
    return np.asarray(argsorted).reshape(Xshape)

In [223]:
M = np.floor(100*np.random.random((3, 3)))
M
# M = np.arange(0, 10, 2)

array([[ 90.,  20.,  14.],
       [ 93.,  61.,   5.],
       [ 89.,  38.,  87.]])

In [243]:
M.argsort()

array([[2, 1, 0],
       [2, 1, 0],
       [1, 2, 0]])

In [242]:
np.argsort(M)

array([[2, 1, 0],
       [2, 1, 0],
       [1, 2, 0]])

In [224]:
temp_array = np.array([2,3,55,6,324,24,234,-9])

In [225]:
temp_array

array([  2,   3,  55,   6, 324,  24, 234,  -9])

In [234]:
np.argsort(temp_array)

array([7, 0, 1, 3, 5, 2, 6, 4])