In [1]:
import numpy as np

## Min function

In [18]:
def min(X):
    """Returns the minimum value. """
    X.sort()
    return X.flatten()[0]

In [19]:
X = np.arange(9).reshape(3, 3)

In [20]:
X.min() == min(X)

True

## Max Function implementation

In [22]:
def max(X):
    """Returns the maximum value. """
    X.sort()
    Xmax = X.flatten()[-1]
    return 

In [23]:
X = np.arange(9).reshape(3, 3)

In [24]:
X.max == max(X)

False

## Argmin Function implmentation

In [39]:
def argmin(X):
    """Returns the indices of the minimum value. """
    flatten_matrix = X.flatten()
    min_value = flatten_matrix.min()
    return flatten_matrix.tolist().index(min_value)
    

In [40]:
X = np.arange(9).reshape(3, 3)

In [41]:
X.argmin() == argmin(X)

True

## Argmax Function Implementation

In [44]:
def argmax(X):
    """Returns the indices of the maximum value. """
    flatten_matrix = X.flatten()
    max_value = flatten_matrix.max()
    return flatten_matrix.tolist().index(max_value)

In [45]:
X = np.arange(9).reshape(3, 3)

In [47]:
X.argmax() == argmax(X)

True

## Transpose of a Matrix

In [66]:
def transpose(X):
    """ Returns the transpose of the 2d matrix. """
    transposed_matrix = np.zeros(X.shape)
    print (X.shape)
    rows, cols = X.shape
    for i in range(rows):
        for j in range(cols):
            transposed_matrix[j][i] = X[i][j]
    return transposed_matrix

In [67]:
X = np.arange(9).reshape(3, 3)

In [71]:
X.T == transpose(X)

(3, 3)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## Inverse of a matrix

In [227]:
from numpy.linalg import inv
from numpy.linalg import det

In [228]:
def minor(arr,i,j):
    return arr[np.array(list(range(i))+list(range(i+1,arr.shape[0])))[:,np.newaxis], np.array(list(range(j))+list(range(j+1,arr.shape[1])))]

In [229]:
def adjoint(M):
    """Returns the cofactor of a 2d Matrix. """
    cofactor_matrix = np.zeros(M.shape)
    rows, cols = M.shape
    for i in range(rows):
        for j in range(cols):
            cofactor_matrix[i][j] = det(minor(M, i, j))
    cofactor_matrix[1::2, ::2] *= -1
    cofactor_matrix[::2, 1::2] *= -1
    return cofactor_matrix.T

In [230]:
def inverse(X):
    """Returns thr inverse of the matrix X. """
    return adjoint(X) / det(X)

In [249]:
inversed_matrix = inverse(X)

In [250]:
inv_matrix = inv(X)

In [257]:
np.allclose(inversed_matrix, inv_matrix)

True

## Flatten Implementation

In [73]:
def flatten(X):
    """Returns the flatten matrix. """
    # np.nditer iterates over an iterable array and then
    return np.fromiter(np.nditer(X), X.dtype)

In [74]:
M = np.arange(9).reshape(3, 3)

In [75]:
flatten(M) == M.flatten()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

## Dot Product

In [80]:
def dot(X, Y):
    """Returns the dot product. """
    Xrows, Xcols = X.shape
    Yrows, Ycols = Y.shape
    DotProduct = np.zeros(shape=(Xrows, Ycols))
    if Xcols == Yrows:
        for i in range(Xrows):
            for j in range(Xcols):
                sum = 0
                for k in range(Yrows):
                    sum += X[i][k] * Y[k][j]
                DotProduct[i][j] = sum
        return DotProduct
    else:
        
                
    

In [84]:
X = np.arange(9).reshape(3, 3)
Y = np.arange(9).reshape(3, 3)

In [85]:
dot(X, Y) == X.dot(Y)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## Arange followed by reshaper

In [143]:
def arange_reshape(start, stop, shape):
    rows, cols = shape
    matrix = np.zeros(shape)
    range_of_numbers = list(range(start, stop))
    diff = stop - start
    if(diff == shape[0]*shape[1]):
        it = iter(range_of_numbers)
        for i in range(rows):
            for j in range(cols):
                matrix[i][j] = it.__next__()
        return matrix
    else:
        print("Total size of new array should be unchanged")

In [150]:
arange_reshape(2, 6, (2, 2)) == np.arange(start=2,stop=6,step=1).reshape(2, 2)

array([[ True,  True],
       [ True,  True]], dtype=bool)

## Argsort

In [3]:
def argsort(X, axis=1):
    argsorted = []
    Xrows = X.shape[0]
    Xshape = X.shape
    if(X.ndim == 1):
        X = [X]
        Xrows = 1
    if (axis == 0):
        print("Axis")
        X = X.T
    for i in range(Xrows):
        row = X[i].tolist()
        row.sort()
        for j in np.nditer(X[i]):
            argsorted.append(row.index(j))
    if(axis == 0):
        print("Axis")
        return np.asarray(argsorted).reshape(Xshape).T
    return np.asarray(argsorted).reshape(Xshape)

In [132]:
M = np.floor(100*np.random.random((3, 3)))
M
# M = np.arange(0, 10, 2)

array([[ 84.,   7.,   9.],
       [ 55.,  42.,  76.],
       [ 88.,  28.,  22.]])

In [129]:
M.argsort() == argsort(M)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]], dtype=bool)

In [133]:
M.argsort()

array([[1, 2, 0],
       [1, 0, 2],
       [2, 1, 0]])

In [149]:
np.argsort(M)

import numpy as npc

m = npc.array([84., 7., 9.])
print(m)
print(npc.argsort(, -1))



[ 84.   7.   9.]
[1 2 0]


## Identity Implementation

In [150]:
def identity(n):
    """Returns th identity matrix for a given row and column count. """
    matrix = np.zeros((n, n))
    np.fill_diagonal(matrix, 1)
    return matrix

In [151]:
identity(3) == np.identity(3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## Eye Implementation

In [64]:
def eye(N, M, k):
    """Returns a 2d array with ones on the diagonal and zeros elsewhere. """
    zero_matrix = np.zeros((N, M))
    diag_indices = np.diag_indices(N, M)
    if(k < 0):
        print("K lesser than 0")
        shifted_indices = diag_indices[0] + [abs(k)] * len(diag_indices[0])
        shifted_diag_indices = (shifted_indices[0:len(shifted_indices)-abs(k)], diag_indices[1][0:len(shifted_indices)-abs(k)])
    else:
        print("K greater than 0")
        shifted_indices = diag_indices[1] + [abs(k)] * len(diag_indices[1])
        shifted_diag_indices = (diag_indices[0][0:len(shifted_indices)-abs(k)], shifted_indices[0:len(shifted_indices)-abs(k)])
    zero_matrix[shifted_diag_indices] = 1
    return zero_matrix
    

In [65]:
eye(4, 4, -1) == np.eye(4, 4, -1)

K lesser than 0


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

## Sum Implementation

In [66]:
def sum(X, Y):
    return X + Y

In [67]:
X = np.arange(9).reshape(3, 3)
Y = np.arange(9).reshape(3, 3)

In [74]:
sum(X, Y) == np.add(X, Y)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## Diagonal Matrix

In [80]:
def diagonal(X):
    """Returns the Diagonal elements of the matrix. """
    return [X[i][i] for i in range(len(X))]

In [81]:
X = np.arange(9).reshape(3, 3)

In [84]:
diagonal(X) == np.diag(X)

array([ True,  True,  True], dtype=bool)

## Upper Triangulation Matrix

In [120]:
def triu(X):
    zeros = np.zeros(X.shape)
    zeros[np.triu_indices(X.shape[0])] = X[np.triu_indices(X.shape[0])]
    return zeros


In [121]:
X = np.random.random((4, 4))

In [122]:
triu(X)

array([[ 0.06564349,  0.95793363,  0.12972385,  0.96876599],
       [ 0.        ,  0.15128879,  0.25285629,  0.33641538],
       [ 0.        ,  0.        ,  0.24654317,  0.99827746],
       [ 0.        ,  0.        ,  0.        ,  0.40717975]])

## Lower Triangulation Matrix

In [123]:
def tril(X):
    zeros = np.zeros(X.shape)
    zeros[np.tril_indices(X.shape[0])] = X[np.tril_indices(X.shape[0])]
    return zeros

In [124]:
tril(X)

array([[ 0.06564349,  0.        ,  0.        ,  0.        ],
       [ 0.19537082,  0.15128879,  0.        ,  0.        ],
       [ 0.50732134,  0.71840764,  0.24654317,  0.        ],
       [ 0.15745887,  0.73191048,  0.83352938,  0.40717975]])

In [191]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
