In [7]:
import numpy as np

## Consider a generator function that generates 10 integers and use it to build an array

In [5]:
def generate():
    for x in range(25):
        yield x

In [6]:
np.fromiter(generate(), dtype=float, count=-1)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.])

## Convert the Cartesian Coordinates to Polar Coordinates

In [14]:
Z = np.random.random((10, 2))

array([[ 0.42015214,  0.41792412],
       [ 0.42450798,  0.27091407],
       [ 0.49289123,  0.69635513],
       [ 0.69540205,  0.35873655],
       [ 0.06532448,  0.04597916],
       [ 0.7190098 ,  0.25728366],
       [ 0.74020853,  0.354     ],
       [ 0.51589369,  0.43000397],
       [ 0.79930338,  0.54039253],
       [ 0.71967982,  0.25997476]])

In [13]:
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[ 0.80275248  0.58024822  0.31634035  0.57495811  0.17065143  0.49838694
  0.87538378  0.67325787  0.96726753  0.12913409]
[ 0.08325807  0.29132686  0.59133478  0.41158461  0.10228901  0.88437902
  0.03355543  0.11377132  0.29996262  0.0307325 ]
[ 0.80705852  0.64927601  0.67063257  0.70709173  0.19895967  1.01514324
  0.87602667  0.6828031   1.01271123  0.13274073]
[ 0.10334624  0.46530449  1.07957356  0.6212855   0.53998057  1.05761377
  0.03831349  0.16740472  0.30070913  0.23364272]


## Get N largest elements in a array

In [30]:
Z = np.arange(10000)

In [40]:
np.random.shuffle(Z)
print(Z)

[1379 7005 6782 ..., 8542  936 1124]


In [42]:
sortedIndex = np.argsort(Z)

In [50]:
Z[sortedIndex][-10:]

array([9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9999])

## Create a 3x3x3 array with random values

In [51]:
np.random.random((3, 3, 3 ))

array([[[ 0.51936195,  0.42535873,  0.56290867],
        [ 0.23766867,  0.0657398 ,  0.57934848],
        [ 0.29681864,  0.98270058,  0.35020673]],

       [[ 0.45569413,  0.12773342,  0.42387441],
        [ 0.7348236 ,  0.00613982,  0.86680869],
        [ 0.26212119,  0.86755021,  0.65918915]],

       [[ 0.28567849,  0.09451365,  0.89331598],
        [ 0.53873176,  0.42065315,  0.65882938],
        [ 0.90627442,  0.89574278,  0.90321413]]])

## Bincount